import { Dot } from '../models/Dot';

export const dots: Array<Dot> = [
  {
    title: 'Who I am',
    id: '0',
    text: 'Front End developer specialised in JavaScript technologies, experienced with Node, React, Typescript. Love building apps with great teams and always looking forward for the next challenge!',
    hidden: false,
    centroid: { x: 210, y: 60 },
    next: ['1', '2', '3'],
    hit: false,
  },
  {
    title: 'Facile.it',
    id: '1',
    text: 'Facile.it is .... I worked as Front End developer with the following tech stack: React, TS.',
    hidden: true,
    centroid: { x: 60, y: 160 },
    next: [],
    hit: false,
  },
  {
    hit: false,
    title: 'Auriga',
    id: '2',
    text: 'Auriga is a key player, at an international level, in the creation of proprietary software solutions, specialising particularly in Banking area.',
    hidden: true,
    centroid: { x: 260, y: 160 },
    next: ['3'],
  },
  {
    hit: false,

    title: 'NTT Data',
    id: '3',
    text: 'NTT DATA is a global IT innovator. Worked in Digital Entity (design studio) as Front End Developer.',
    hidden: true,
    centroid: { x: 460, y: 160 },
    next: ['4', '5', '6', '7'],
  },
  {
    hit: false,
    title: 'Codeworks',
    id: '4',
    text: 'Codeworks',
    hidden: true,
    centroid: { x: 70, y: 280 },
    next: [],
  },
  {
    hit: false,
    title: 'Hasselt',
    id: '5',
    text: 'Hasselt',
    hidden: true,
    centroid: { x: 200, y: 290 },
    next: [],
  },
  {
    hit: false,
    title: 'Siena',
    id: '6',
    text: 'Siena',
    hidden: true,
    centroid: { x: 320, y: 260 },
    next: [],
  },
  {
    hit: false,
    title: 'Bologna',
    id: '7',
    text: 'Bologna',
    hidden: true,
    centroid: { x: 410, y: 320 },
    next: [],
  },
];
